### ISSUE TITLE
Error when using with latest Tangram 0.11 

### ISSUE THREAD

**Issue by mattrei** [tangrams/heightmapper#12]
Hi,

when updating the include script line of the index.html to the latest tangram Version, Tangram breaks with an error on the scene.yaml file, saying
`
Tangram v0.11.8 [error]: ERROR: 0:24: 'u_max' : syntax error 
`

The yaml file however works in the Tangram Play editor. The documentation also does not clarify things why it breaks, as seen here https://mapzen.com/documentation/tangram/Shaders-Overview/#shaders-inside-tangram

Thanks for your help.

Best

**Comment by meetar** [comment]
Fixed with https://github.com/tangrams/heightmapper/commit/af56fa2e1529dedc48b6fa626a0b38554e567283 – I was attempting to set these uniforms to `undefined`, up with which Tangram 0.11.1 and on will no longer put :D

Thanks for the tip @mattrei!
