### ISSUE TITLE
any reason the fake3d branch is stopped?

### ISSUE THREAD

**Issue by morandd** [tangrams/heightmapper#13]
is there any fundamental reason the fake3d branch is abandoned? Did you run into some big problem, or was it just lack of time?

**Comment by meetar** [comment]
tbh I don't remember exactly what's going on here. It looks like I was trying to borrow a bunch of camera interaction stuff from another demo I'd done, and then I probably ran out of time. But it's still a good idea and I'd like to return to it – I plan to have more time this fall for experiments like this.

**Comment by meetar** [comment]
Closing as historical, no plans to return to this.
