### ISSUE TITLE
It is not possible to hide the map labels

### ISSUE THREAD

**Issue by MichaelVortex** [tangrams/heightmapper#14]
I've tried to hide the map labels but it's not possible. 
Any ideas?

///EDIT/// I think this function is not working:

`function toggleLabels(active) {
        // scene.config.layers.water.visible = active;
        scene.styles.toggletext.shaders.uniforms.u_alpha = active ? 1. : 0.;
        scene.requestRedraw();
    }`

![heightmapper](https://user-images.githubusercontent.com/20084410/29656840-f543f18a-88b5-11e7-91fd-e3489cc54c80.jpg)

**Comment by meetar** [comment]
@MichaelVortex You're right, a related piece of functionality changed in the underlying code, so the label-toggling method will have to be updated. Thanks for the report!

**Comment by meetar** [comment]
Patched temporarily with https://github.com/tangrams/heightmapper/commit/af431edc7c5bdb141ca0f91390eac37b928c055c

**Comment by MichaelVortex** [comment]
Thank you!!!
