### ISSUE TITLE
Export not working in Windows (both Chrome and IE) in Win10

### ISSUE THREAD

**Issue by hurricanz** [tangrams/heightmapper#15]
I've tried both Chrome (Version 60.0.3112.113 (Official Build) (64-bit))  and IE (Edge 40.15063.0.0) in Win 10 but when I hit EXPORT a blank page pops up with nothing on it.   So the pop-up is working, it's just nothing is getting passed to it.

**Comment by hurricanz** [comment]
still doesn't work and doesn't look like it was acknowledged by the team.  Any ETA on this?

**Comment by meetar** [comment]
Hi @hurricanz – sorry I missed this, I'll take a look.

**Comment by meetar** [comment]
Confirmed was broken everywhere. Fixed with https://github.com/tangrams/heightmapper/commit/0896a751f982f891afe1cda73f44033b507e73c8
