### ISSUE TITLE
38.8570,-79.8962

### ISSUE THREAD

**Issue by PFPF** [tangrams/heightmapper#21]
https://tangrams.github.io/heightmapper/#12.89447/38.8570/-79.8962
Any reason why there's some 8900m mountain in that region?

**Comment by meetar** [comment]
Yep! It's a data glitch of unknown origin. Unfortunately this is unlikely to be fixed until somebody runs a terrain build again - check out https://github.com/tilezen/joerd for more information. Thanks for your interest!
