### ISSUE TITLE
Help - link

### ISSUE THREAD

**Issue by mond-cz** [tangrams/heightmapper#23]
Just a small thing - under "Help" the link "import to Blender" is broken.
BTW any chance for 16 or 32 bit export?
Anyway - AWESOME tool .) Thanks

**Comment by meetar** [comment]
It sure was, thanks! The correct url should have been "https://github.com/tangrams/heightmapper/blob/master/exporting_to_blender.md" – hope it's useful!

And better export options are definitely top of the list 😅 

Thanks for the feedback!

**Comment by mond-cz** [comment]
I was just referring to your work in this Tut. 
https://blender.stackexchange.com/questions/158749/modeling-a-low-poly-crater-in-blender/158755?noredirect=1#comment269089_158755

I'm looking forward :) Thank you
