### ISSUE TITLE
Impossible to get heightmap data

### ISSUE THREAD

**Issue by Xcavate54** [tangrams/heightmapper#25]
Trying to get heightmap data for a popular motocross track to replicate it in a video game, and every time I zoom in past "#7", I get an all white image, rather than grayscale. Image included for reference
![boo](https://user-images.githubusercontent.com/67409539/85673069-82408100-b691-11ea-840c-b3fbbf4f4a19.png)

**Comment by Manu252** [comment]
Anche a me lo stesso problema, devo creare circuiti di motocross e quando vado ad ingrandire è tutto bianco

**Comment by drewgriz** [comment]
I'm having the same issue, it looks like nowhere on the globe shows data past zoom level 7.

**Comment by meetar** [comment]
Issue resolved itself – best guess is that too many people hitting the service caused rate limiting. ¯\_(ツ)_/¯
