### ISSUE TITLE
Heightmap glitches

### ISSUE THREAD

**Issue by Dechetmew** [tangrams/heightmapper#26]
When i export, i get this:
![heightmapper-1598460671430](https://user-images.githubusercontent.com/63635533/91332949-2eefc980-e7cd-11ea-953f-796a9ae1ddfe.png)

Please fix this

**Comment by meetar** [comment]
Could you try it again now?

**Comment by Dechetmew** [comment]
Ok, i tried it again and it works perfectly now. Yesterday i even Reloaded the page several times even checked my connection and nothing helped. And today, it magicaly works. I think it was happening beacuse of more people were online (maybe) at that time.
This happens quite often to me even on other computers. Try to fix this somehow as its very annoying.

**Comment by meetar** [comment]
Yep, unfortunately this is an upstream issue, there's not really anything you or I can do about it. It's definitely related to the servers that the tiles are stored on, which are managed by the Nextzen admins. If you check your network tab the next time this happens you can get more information about the problem - if you see 429 errors it's probably rate-limiting as you suggest, and if you see 503 errors it means a server is down or the cache is full or something like that.

Sorry for the trouble, and good luck!
