### ISSUE TITLE
Missing data tiles

### ISSUE THREAD

**Issue by 2TallTyler** [tangrams/heightmapper#27]
For several months I've been experiencing a problem where data tiles don't load at certain zoom levels. Zooming in or out often loads tiles for those areas, but then others disappear. This happens on multiple computers and operating systems.

I see this every time I've loaded Heightmapper over the past 6 months or so, but I haven't noticed if it's the same times every time.

![heightmapper-1606961008045](https://user-images.githubusercontent.com/55058389/100954192-11c04a80-34e2-11eb-9db8-1b9cb79e5900.png)

**Comment by meetar** [comment]
Yep performance has been iffy since @mapzen closed down, apologies for the trouble – try it again?

**Comment by 2TallTyler** [comment]
Fixed. Thank you!
