### ISSUE TITLE
Contour Lines on map

### ISSUE THREAD

**Issue by EndIris** [tangrams/heightmapper#31]
I visited the website for the first time in about two months, and noticed that what was formerly a beautiful smooth gradient now has ugly contour lines all over it. This may be an issue with the source maps, but I find that unlikely. Please remove the contour lines if possible.

**Comment by meetar** [comment]
The scene file hasn’t been changed in two years, so the source data is implicated. I am seeing a glitch at 256 meters elevation, which is certainly a bug. I’m not sure whether this data is being updated or who is responsible for it, but I’ll ask around.

**Comment by Gelpegertje** [comment]
I also find these lines annoying (the line at 0-meters especially). Is there any development on this issue? Thanks.

**Comment by EndIris** [comment]
Interestingly, I found that the lines aren't present on my old home computer. I checked and they are running the same version of chrome, so maybe it has something to do with windows as those versions aren't the same (19041 Pro vs 19043 Enterprise). I also can confirm that the lines occur at every 256 meters elevation, so at 256, 512, 768 etc.

**Comment by baardrg** [comment]
Having same issue. It's present at all maps, making it impossible to use the high maps for creating 3D landscapes with it. The black lines becomes deep trenches in the terrain. I have tried three different browsers but all on the same machine running Windows 11. I do howevere experience the same issue on my Android cell phone, so doesn't seem to be a Windows issue only...
![render (1)](https://user-images.githubusercontent.com/67283561/230773613-6215291f-f7ff-431d-9d1c-d7e66e7f188f.png)
![feil_i_map1](https://user-images.githubusercontent.com/67283561/230773932-6afa6a1f-ee1b-4fe6-98a1-42b7afb1b632.jpg)

**Comment by EndIris** [comment]
I'm gonna go ahead and close this seen as it is no longer an issue on my end. Someone else may reopen if they see fit.
