### ISSUE TITLE
Tile load failure? Maybe?

### ISSUE THREAD

**Issue by wboykinm** [tangrams/heightmapper#6]
I actually have no idea what to make of this:

![bug](https://www.dropbox.com/s/yevolyzzgc5tg5b/Screenshot%202016-09-13%2017.21.15.png?dl=1)

URL: https://tangrams.github.io/heightmapper/#12.72104/42.2820/-70.9532

Nothing at the console except a favicon 404.

**Comment by jan-tosovsky-cz** [comment]
See the strange elevation range, the another case for https://github.com/tilezen/joerd/issues/96

**Comment by jan-tosovsky-cz** [comment]
One of problematic source tiles: https://terrain-preview.mapzen.com/terrarium/12/1240/1516.png

**Comment by meetar** [comment]
Yep, very strange data – don't think it's a loading failure… could be related to the joerd#96 issue, as @jan-tosovsky-cz mentioned, but looks a little more like a tile-generation process failed. Passing the buck to the tiles crew: https://github.com/tilezen/joerd/issues/99
